config/routes.rb
Rails.application.routes.draw do
  resources :employees, only:[:show, :index, :destroy,:create,:new,:edit,:update]

  root 'pages#home'
  # get 'employees/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  before_save {self.name = name.upcase}
  before_save {self.address = address.upcase}
  validates :name, presence: true
  validates :address, presence: true
  # belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only:[:show,:edit,:update,:destroy]
  def show
  end

  def index
    @emp = Employee.all
  end

  def new
    @emp =Employee.new
  end

  def edit
  end

  def create
    @emp=Employee.new(set_params)
    @emp.save
    redirect_to employees_path
  end

  def update
    @emp.update(set_params)
    redirect_to employees_path
  end

  def destroy

    @emp.destroy

  end
  private
  def set_employee
    @emp=Employee.find(params[:id])
  end
  def set_params
    params.require(:employee).permit(:name,:address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_form.html.erb
<%= form_with(model:@emp,local: true) do |f| %>

  <p><%= f.label :name %>
    <%= f.text_area :name %>
  </p>

  <p><%= f.label :address %>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end %>

app/views/employees/edit.html.erb
<h1>EDIT EXISTING EMPLOYEE DETAILS</h1>
<%= render 'form' %>
<p>
<%=link_to 'PREV PAGE', employees_path %>
</p>

app/views/employees/index.html.erb
<h1>LISTING PAGE</h1>
<table>
  <thead>
  <tr>
    <th>NAME</th>
    <th>ADDRESS</th>
    <th>OPTION</th>
  </tr>
  </thead>

  <tbody>
  <% @emp.each do |emp| %>
  <tr>
    <td><%= emp.name %></td>
    <td><%= emp.address %></td>
    <td><%=link_to 'Show',employee_path(emp)%></td>
    <td><%=link_to 'Edit',edit_employee_path(emp)%></td>
    <td> <%= button_to 'Delete', emp, method: :delete %></td>
  </tr>
  </tbody>
<%end %>
</table>
<p>
<td><%=link_to 'CREATE NEW',new_employee_path(@emp)%></td>
</p>

app/views/employees/new.html.erb
<h1> CREATING NEW EMPLOYEE DETAILS</h1>
<%= render 'form'%>
<p>
<%=link_to 'LISTING PAGE', employees_path %>
</p>

app/views/employees/show.html.erb
<h1> Employee Management System</h1>
<p><strong>NAME:</strong><%= @emp.name %></p>
<p><strong>ADDRESS:</strong><%= @emp.address %></p>
<%=link_to 'PREV PAGE',employees_path(@emp)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>WELCOME..! </h1>
<%=link_to 'LISTING PAGE',employees_path %>